### PR TITLE
Tidy CDK Commands

### PR DESCRIPTION
**Pull request by awschristou**
## Description

This change cleans up some of the experience around commands and the Command Palette for consistency within the toolkit.

* The Refresh commands were renamed from "Refresh" to "Refresh AWS Explorer" and "Refresh CDK Explorer" to disambiguate the commands
  * They show as tooltips:
image

* The "Refresh CDK Explorer" command has been removed from the Command Palette (it is accessible from the CDK Explorer, and this parallels the AWS Explorer's refresh functionality)
* The "Provide Feedback" command that is available from the CDK Explorer has been removed from the Command Palette to avoid confusion with the "Report an Issue" command
* The "Refresh CDK Explorer" command has been added to the extension activation list in order to prevent a "command not found" error message if the command is clicked before the extension fully activates

## Testing

Manually tested in-toolkit:
* Verified that the AWS Explorer and CDK Explorer's refresh commands have the updated tooltip
* Verified that the Refresh command for CDK Explorer is no longer in the Command Palette
* Verified that the Provide Feedback command for CDK Explorer is no longer in the Command Palette
* Clicked the "Refresh CDK Explorer" button as soon as VS Code loads and before the toolkit is activated, to ensure the error message no longer occurs

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by justinmk3** [comment]
>     The Refresh commands were renamed from "Refresh" to "Refresh AWS Explorer" and "Refresh CDK Explorer" to disambiguate the commands

Would this set a precedent for appending the name to every tooltip?

Seems unnecessarily verbose, given that the context is very clear by the placement of each button: in the screenshots, the buttons are literally adjacent to "AWS EXPLORER" and "AWS CDK EXPLORER", respectively.

**Comment by awschristou** [comment]
> Would this set a precedent for appending the name to every tooltip?
>
> Seems unnecessarily verbose, given that the context is very clear by the placement of each button: in the screenshots, the buttons are literally adjacent to "AWS EXPLORER" and "AWS CDK EXPLORER", respectively.

It helps particularly when commands can be wired into other parts of VS Code. For example, we had an older bug where the commands appeared on all other VS Code extension views, and we had the CDK's command in the Command Palette (until this PR), which appeared as "Refresh". In both scenarios, the command is insufficient to explain what system it relates to.

**Comment by justinmk3** [comment]
> and we had the CDK's command in the Command Palette

Ah, I missed that this also affects the global command palette.  Then I wonder about other things like `"AWS.command.configureLambda": "Configure"`, but I assume there's some knob where it is decided whether these things show up in the palette.

**Comment by awschristou** [comment]
> Ah, I missed that this also affects the global command palette.  Then I wonder about other things like `"AWS.command.configureLambda": "Configure"`, but I assume there's some knob where it is decided whether these things show up in the palette.

Yup, this is how commands are configured to not show in the palette: https://github.com/aws/aws-toolkit-vscode/pull/839/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R163

**Pull request merged**
