### PR TITLE
SSM: update changelog entry, readme

### PR DESCRIPTION
**Pull request by feiyao-aws**
…elog entry

## Description
Added changelog to summarize new Systems Manager features
Removed old changelog
Small updates to readme

## Checklist

- [x] I have read the **README** document
- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] A short description of the change has been added to the changelog using the script `npm run newChange`

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bryceitoc9** [comment]
Changing merge branch to `master` since https://github.com/aws/aws-toolkit-vscode/pull/1321 was merged.

**Comment by feiyao-aws** [comment]
Branch already merged with master

**Comment by feiyao-aws** [comment]
Rebased from master, squashing commits.

**Review by bryceitoc9 — APPROVED** [review]

**Pull request merged**
