### PR TITLE
integ: fix ENOSPC

### PR DESCRIPTION
**Pull request by JadenSimon**
Cleanup files after running tests.

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by justinmk3 — APPROVED** [review]

**Comment by bryceitoc9** [comment]
Make sure to give this at least two or three full runs if the first comes back successful.

**Comment by JadenSimon** [comment]
Nope still didn't work. Need to figure out a way to restart the language server.

**Comment by JadenSimon** [comment]
After experimenting, it looks like the Java extension is pretty 'dumb' with how it handles projects. Whenever we create a new lambda, it is still referring back to the original project. So deleting it causes issues and basically breaks the extension. There's no way to reset the language server without restarting VS Code, otherwise this wouldn't be a big deal. 

I increased the watcher limit for the CodeBuild job which should fix the issue (assuming it lets me change it). The long-term solution would be to run each lambda integ test in it's own workspace, restarting VS Code each time.

**Review by justinmk3 — APPROVED** [review]
If this unblocks the CI then we can try it. 

This has a slight risk of allowing a regression in our file watcher logic. We can track this in our backlog item for parallelizing the integ tests.

**Comment by JadenSimon** [comment]
CodeLens failures stopped, running into some attachment failures though for unrelated runtimes.

**Pull request merged**
