### PR TITLE
UI: statusbar UX

### PR DESCRIPTION
**Pull request by justinmk3**
From VSCode UI guidelines: https://code.visualstudio.com/api/references/extension-guidelines#status-bar

> Place primary (global) items on the left
> Place secondary (contextual) items on the right

Toolkit AWS connect status is "global", so it should be on the left.

image

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by bryceitoc9 — APPROVED** [review]

**Review by JadenSimon — APPROVED** [review]
Might confuse some users initially, though it should still be moved.
Also, changelog

**Comment by breedloj** [comment]
We might want to reconsider the item priority with this change too. At `100` this appears before the code problems item which realistically is going to be interacted with a lot more often.

**Comment by justinmk3** [comment]
updated

- changed priority=1
- take less space when not connected
- improve tooltip message
- updated screenshot

**Pull request merged**
