### PR TITLE
feat(amazonq): Rename CodeWhisperer to Amazon Q. Part 1

### PR DESCRIPTION
**Pull request by leigaol**
## Problem

As a product requirement, all customer facing CodeWhisperer mentions need to be renamed into Amazon Q.

## Solution

Rename customer facing CodeWhisperer mentions. 

Note: There will be part 2, part3 PRs. This one does not rename settings & comands yet. 

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by justinmk3 — APPROVED** [review]

**Comment by justinmk3** [comment]
This is failing a new test : 

```
  21) AuthUtil
       should show reauthenticate prompt:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'Connection expired. To continue using Amazon Q, connect with AWS Builder ID or AWS IAM Identity center.'
- 'Connection expired. To continue using Amazon Q/CodeWhisperer, connect with AWS Builder ID or AWS IAM Identity center.'
      + expected - actual

      -Connection expired. To continue using Amazon Q, connect with AWS Builder ID or AWS IAM Identity center.
      +Connection expired. To continue using Amazon Q/CodeWhisperer, connect with AWS Builder ID or AWS IAM Identity center.
      
      at Context.<anonymous> (src/test/codewhisperer/util/authUtil.test.ts:125:16)
```

**Comment by leigaol** [comment]
> This is failing a new test :
> 
> ```
>   21) AuthUtil
>        should show reauthenticate prompt:
> 
>       AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
> + actual - expected
> 
> + 'Connection expired. To continue using Amazon Q, connect with AWS Builder ID or AWS IAM Identity center.'
> - 'Connection expired. To continue using Amazon Q/CodeWhisperer, connect with AWS Builder ID or AWS IAM Identity center.'
>       + expected - actual
> 
>       -Connection expired. To continue using Amazon Q, connect with AWS Builder ID or AWS IAM Identity center.
>       +Connection expired. To continue using Amazon Q/CodeWhisperer, connect with AWS Builder ID or AWS IAM Identity center.
>       
>       at Context.<anonymous> (src/test/codewhisperer/util/authUtil.test.ts:125:16)
> ```

Fixed in latest commit.

**Review by justinmk3 — APPROVED** [review]
Let's wait until @hayemaxi merges https://github.com/aws/aws-toolkit-vscode/pull/4669

**Comment by leigaol** [comment]
> Let's wait until @hayemaxi merges #4669

This is merged.

**Pull request merged**
