### PR TITLE
telemetry: record arch in "Create SAM App" resume

### PR DESCRIPTION
**Pull request by justinmk3**
## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by JadenSimon — COMMENTED** [review]
Need to update the call to `setSamInitState` right?
We probably should tweak the types to make all the fields required for the call (but can be undefined)

**Comment by justinmk3** [comment]
> Need to update the call to `setSamInitState` right? 

line 261. or do you mean something else?

> We probably should tweak the types to make all the fields required for the call (but can be undefined)

Lots of changes needed to this subsystem. E.g. could store the whole object instead of setting separate fields. Also need type-checking for the rehydrated result... :)

**Comment by JadenSimon** [comment]
> line 261. or do you mean something else?

Nvm Github was hiding the call.

**Review by JadenSimon — APPROVED** [review]

**Comment by JadenSimon** [comment]
> could store the whole object instead of setting separate fields. Also need type-checking for the rehydrated result.

Yup, could just attach the state saving to the wizard's run promise. The less disconnected mappings the better.

**Pull request merged**
