### PR TITLE
SAM debug: retry only once

### PR DESCRIPTION
**Pull request by justinmk3**
Retrying more than once is a bad experience: VSCode will show the
debugger UI again and again, and user must hit the "Stop" button every
time we retry.

TODO: can we listen to the "Stop" button and cancel retries then?

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bryceitoc9** [comment]
> TODO: can we listen to the "Stop" button and cancel retries then?

I'm kinda thinking this ties into the `onDidTerminateDebugSession` hook, but I think that the debugger dying and restarting also triggers that. I'm not sure if there's a good way to measure the failure and let it retry unless the user explicitly opts-out with the stop button (vs. clicking through the debugger failure)

**Comment by justinmk3** [comment]
> I'm not sure if there's a good way to measure the failure and let it retry unless the user explicitly opts-out with the stop button (vs. clicking through the debugger failure)

If there is a way to detect Stop button, that is what I would like here.

**Comment by JadenSimon** [comment]
Couldn't find any way to detect click events for the debugging interface. Maybe we can make the number of retries a setting but default it to 1? This gives users control over it in case they actually needed the retry functionality.

**Comment by justinmk3** [comment]
This is too obscure to expose to users. We just need to default to 1. Waiting for approval.

**Review by JadenSimon — APPROVED** [review]
Fair enough. I suppose it should be up to the Toolkit to know when to automatically retry, not the user.

**Pull request merged**
