### PR TITLE
build: remove mocha-multi-reporters + mocha-junit-reporters

### PR DESCRIPTION
**Pull request by JadenSimon**
These two deps are not being used other than generating a `report.xml` file that is not consumed by any automation tools (that I know of). We can add them back later when it's clear that we need a Mocha report in XML format.

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by justinmk3** [comment]
the failing `Integration Tests [insiders]` job is the same as in https://github.com/aws/aws-toolkit-vscode/pull/1811 , so unrelated to this PR. Likely an upstream change.

**Review by justinmk3 — APPROVED** [review]

**Comment by justinmk3** [comment]
> generating a `report.xml` file that is not consumed by any automation tools (that I know of).

I think it's used by the "Test report" tab of the CI HTML page. compare the [master build](https://d1ihu6zq92vp9p.cloudfront.net/627f7b1d-5d04-434b-8028-b1e63ef56ca3/report.html).

Also the "Test Summary" now shows 0 for the test counts. So I guess we need the xml stuff :(

**Comment by JadenSimon** [comment]
Yup that's unfortunate. Mocha should let us output to multiple sources instead of forcing us to take two dependencies just for that functionality...

**Pull request closed without merging**
