### PR TITLE
feat: dynamic resource support in AWS Explorer

### PR DESCRIPTION
**Pull request by breedloj**
## Problem
Many resource types are currently unsupported in the AWS Explorer. This forces users to use the console or other tools to discover or check statuses for these resources.

## Solution
This change introduces dynamic support for discovering and interacting with resources in the explorer. CloudControl APIs are used to generically interact with supported resource types.

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by kiiadi — APPROVED** [review]

**Review by justinmk3 — CHANGES_REQUESTED** [review]
imo, this should not ship until we have an approach that avoids lots of items in the user's settings.json. We have had clear feedback that this is unwanted #2112.

Potential ideas:

1. _Remove_ settings after the relevant editor tab/file is closed.
    - Is there any need for the settings to be permanent, as we currently have them?
1. the `fileMatch` could be more generic, e.g. `/*.awsResource.json`
    1. this would require schemas to be combined into a single `schema.json`.
    1. then each resource probably needs to be wrapped in a `{ "type": "...", "value": { <contents> }`

**Comment by breedloj** [comment]
> imo, this should not ship until we have an approach that avoids lots of items in the user's settings.json. We have had clear feedback that this is unwanted #2112.
> 
> Potential ideas:
> 
> 1. _Remove_ settings after the relevant editor tab/file is closed.
>    
>    * Is there any need for the settings to be permanent, as we currently have them?
> 2. the `fileMatch` could be more generic, e.g. `/*.awsResource.json`
>    
>    1. this would require schemas to be combined into a single `schema.json`.
>    2. then each resource probably needs to be wrapped in a `{ "type": "...", "value": { <contents> }`

I have some thoughts on this but I'd like to drive this through a separate PR (I have also created a tracking item for myself). I think more aggressive management of the mappings may be the best solution for now as I really do not want to mutate the structure of the resource def JSON itself.

**Comment by JadenSimon** [comment]
Here's a best-effort solution (if not already implemented):
* Clean settings on start. All dynamic resource schema mappings would be stale at this point
* Attach clean-up logic to `onDidCloseTextDocument`, removing the mapping associated with the document if it exists

**Review by justinmk3 — APPROVED** [review]

**Comment by justinmk3** [comment]
windows CI failure (non-integ), is there a race in the CloudControl tests?

```
  2 failing
  1) ResourceManager
       opens resources in edit mode:
     Error: ENOENT: no such file or directory, open 'D:\C:\Users\RUNNER~1\AppData\Local\Temp\aws-toolkit-vscode\vsctkHBb8Y5\someidentifier.sometype.awsResource.json'
  

  2) ResourceManager
       creates new resource documents:
     Error: ENOENT: no such file or directory, open 'D:\C:\Users\RUNNER~1\AppData\Local\Temp\aws-toolkit-vscode\vsctkX1jmsk\new.sometype.awsResource.json'
```

**Comment by breedloj** [comment]
> windows CI failure (non-integ), is there a race in the CloudControl tests?
> 
> ```
>   2 failing
>   1) ResourceManager
>        opens resources in edit mode:
>      Error: ENOENT: no such file or directory, open 'D:\C:\Users\RUNNER~1\AppData\Local\Temp\aws-toolkit-vscode\vsctkHBb8Y5\someidentifier.sometype.awsResource.json'
>   
> 
>   2) ResourceManager
>        creates new resource documents:
>      Error: ENOENT: no such file or directory, open 'D:\C:\Users\RUNNER~1\AppData\Local\Temp\aws-toolkit-vscode\vsctkX1jmsk\new.sometype.awsResource.json'
> ```

No, turns out incorrect usage of `path` rather than `fsPath` in the tests. You can skate by on Mac but it burns you on Windows.

**Pull request merged**
