### PR TITLE
feat(runtimes): nodejs16.x

### PR DESCRIPTION
**Pull request by justinmk3**
## Problem

sam cli supports nodejs16 now

## Solution

- add nodejs16 as a Toolkit option.
- add to test matrix.

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by JadenSimon — APPROVED** [review]
Is the image type just not working?

**Comment by blakeanator** [comment]
Hoping this gets merged soon

**Comment by JadenSimon** [comment]
https://github.com/aws/aws-sam-cli/pull/3913 should unblock this

**Comment by justinmk3** [comment]
> [aws/aws-sam-cli#3913](https://github.com/aws/aws-sam-cli/pull/3913) should unblock this

confirmed. tested nodejs16 with packagetype=zip and packagetype=image.

1. built aws-sam-cli locally from https://github.com/aws/aws-sam-cli/pull/3913
   ```
   cd aws-sam-cli
   python3 -m virtualenv venv
   ./venv/bin/pip3 install -e .
   ```
2. in AWS Toolkit, set the sam cli location to `/…/aws-sam-cli/venv/bin/sam`
3. AWS Toolkit can now attach and debug a nodejs16 Lambda locally in Docker

**Review by JadenSimon — APPROVED** [review]

**Comment by blakeanator** [comment]
Glad this made it in. Eager for the next release :)

**Pull request merged**
