### PR TITLE
MRU TextDocument cache implementation

### PR DESCRIPTION
**Pull request by Will-ShaoHua**
## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Will-ShaoHua** [comment]
> what problem is this solving
@justinmk3 
we're planing to run an A/B on our CrossFile context.
The status quo (PROD behavior) is we use opened files and sort them by file distance between the file where users trigger CW.
The next step is to sort them by MRU order instead of file distance.

**Comment by justinmk3** [comment]
Did you evaluate existing MRU packages? Would be ideal if we could find a robust and featureful solution, so that we can use this in many other places that require an MRU.

One particularly important feature is to have "visibility" into the memory cost of the MRU so that we can log warnings if it gets too big, or just log total usage of all MRUs in the Toolkit.

**Comment by Will-ShaoHua** [comment]
> Did you evaluate existing MRU packages? Would be ideal if we could find a robust and featureful solution, so that we can use this in many other places that require an MRU.
> 
> One particularly important feature is to have "visibility" into the memory cost of the MRU so that we can log warnings if it gets too big, or just log total usage of all MRUs in the Toolkit.

yea sounds reasonable to me, I will do some search and see if there is better existing library we can use then.

**Comment by Will-ShaoHua** [comment]
FYI, will not need this PR within short term period.

**Comment by Will-ShaoHua** [comment]
replace it with #5576

**Pull request closed without merging**
