### PR TITLE
UI: move CDK Explorer to the AWS panel

### PR DESCRIPTION
**Pull request by justinmk3**
## Problem

There are multiple places where users can find AWS-related elements provided by the Toolkit.

## Solution

Move the CDK Explorer from the default panel to the AWS panel. This helps establish the AWS icon as the single place for all AWS-related resources--both remote and local.

Screen Shot 2021-04-09 at 6 10 35 PM

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by gsweetwood — APPROVED** [review]

**Comment by kiiadi** [comment]
should we use a different term than "explorer" for one of them or remove "explorer" from "cdk explorer"? It seems weird to me to have "explorer" and "cdk explorer"

reckon you either want "remote explorer" / "cdk explorer" or "explorer" / "cdk"

**Comment by justinmk3** [comment]
> should we use a different term than "explorer" for one of them or remove "explorer" from "cdk explorer"? It seems weird to me to have "explorer" and "cdk explorer"

Agreed, I was thinking "CDK".

**Comment by justinmk3** [comment]
same integ failure on master, so not related to this PR.

**Pull request merged**
