### PR TITLE
feat(lambda): python3.13 support

### PR DESCRIPTION
**Pull request by roger-zhangg**
## Problem
closes: #6076 

## Solution

Add support for python3.13 on SAM build/debug and toolkit features
If the underlying SAM CLI is showing error: python3.13 is not supported, Please update your SAM CLI to 1.129.0

---

License: I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by vicheey — APPROVED** [review]

**Review by vicheey — COMMENTED** [review]
Thank you for the fix. The integration tests were not triggered. AWS Toolkit team, please trigger the intg test.

**Comment by nkomonen-amazon** [comment]
Thanks for this!

**Review by nkomonen-amazon — APPROVED** [review]

**Review by jpinkney-aws — APPROVED** [review]

**Pull request merged**
