### PR TITLE
feat(ui): support multipick prompter

### PR DESCRIPTION
**Pull request by roger-zhangg**
## Problem
Currently prompter doesn't support multipick

## Solution
Add a new function `createMultiPick` that supports multipick and can be used in Wizard.
The returned result will be a list encoded by `JSON.stringify` , use `JSON.parse` to recover the list

## Proposed UX
image
```typescript
// define DataQuickPickItem, note you can use `picked: true` to pre-select items in the multipick
const syncFlagItems: DataQuickPickItem<string>[] = [
    {
        label: 'Build in source',
        data: '--build-in-source',
        description: 'Opts in to build project in the source folder. Only for node apps',
    },
    {
        label: 'Code',
        data: '--code',
        description: 'Sync only code resources (Lambda Functions, API Gateway, Step Functions)',
        picked: true,
    }
]

export interface SyncParams {
    readonly syncFlags: string
}

// define the wizard
export class SyncWizard extends Wizard<SyncParams> {
    public constructor() {
        super()
        this.form.syncFlags.bindPrompter(() => {
            return createMultiPick(syncFlagItems, {
                title: 'Specify parameters for sync',
                placeholder: 'Press enter to proceed with highlighted option',
                buttons: createCommonButtons(samSyncUrl),
            })
        })
    }
}

// run the wizard
result = await new SyncWizard().run()

// Use `JSON.parse` to decode to list -> ['--build-in-source','--code']
console.log(JSON.parse(result.syncFlags))
```

## TODO
Add Tests

---

License: I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jpinkney-aws** [comment]
The code itself looks fine to me but I think we should really have tests for something like this before we merge it

**Comment by roger-zhangg** [comment]
Hi @jpinkney-aws Please take another look when available. Thanks!

**Review by justinmk3 — APPROVED** [review]
Tests are passing and the change is isolated, so we can iterate on this if needed. Meanwhile, it's great to have this in mainline. Thank you!

**Review by jpinkney-aws — APPROVED** [review]

**Comment by justinmk3** [comment]
The failing integ tests are perf tests, unrelated to this PR.

**Pull request merged**
