### PR TITLE
tests/integ: Suppress asserts for previous Node debug sessions

### PR DESCRIPTION
**Pull request by JadenSimon**
## Problem
Previous attempt to fix active debug sessions not disappearing failed. This causes tests to fail even though an active debug session does not really affect the debugging of a new session. 

## Solution
* Suppress assertions when the previous debug session was Node (this appears to be the only one that causes this issue)
* The code that forced sessions to quit was removed since it didn't work. 
* Frozen debug sessions will now appear in the session log as a warning. This is to remind us that a problem exists without having to retry integration tests. 
* The time to wait for sessions to disappear was also reduced slightly.

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by justinmk3 — APPROVED** [review]
Reasonable. choices, thanks for explanation. LGTM

**Comment by bryceitoc9** [comment]
Why focus on Node? Should a different hanging runtime cause a failure?

**Comment by JadenSimon** [comment]
My perspective is to just exclude Node since it appears to be a (relatively) common occurrence and thus an expected behavior (even though it is unwanted). If a different kind of session fails to disappear then that behavior is unexpected, so we should fail the test.

**Review by justinmk3 — APPROVED** [review]

**Pull request merged**
