### PR TITLE
tests(codecatalyst): improve reporting when tests fail

### PR DESCRIPTION
**Pull request by JadenSimon**
## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by justinmk3 — APPROVED** [review]

**Comment by justinmk3** [comment]
> Error: Remote SSH extension version is too low [ExtensionVersionTooLow] (expected: 0.98.0)

Oh, do we actually need 0.98 or could we lower the min version?

**Comment by nkomonen-amazon** [comment]
@justinmk3 from IDE-10402 it was mentioned the user had an error with 0.68 and that when they upgraded to 0.98 it was fixed. So no explicit need for 0.98.

If we have a version we want to check we can install that version and reload vscode to see if it breaks

**Comment by JadenSimon** [comment]
Remote SSH `0.74.0` is compatible with minver. Installing this on stable still allows me to connect.

**Pull request merged**
