### PR TITLE
(telemetry): bump toolkit telemetry generator version

### PR DESCRIPTION
**Pull request by Will-ShaoHua**
## Problem
Bump telemetry version to the latest

## Related

https://github.com/aws/aws-toolkit-common/pull/807
https://github.com/aws/aws-toolkit-jetbrains/pull/4770

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Will-ShaoHua** [comment]
miss package-lock file

**Review by dhasani23 — APPROVED** [review]

**Comment by Will-ShaoHua** [comment]
CI failed due to cwspr test compile error

**Review by andrewyuq — APPROVED** [review]

**Comment by Will-ShaoHua** [comment]
```
2521 passing (2m)
  10 pending
  1 failing
  1) generateResourceHandler
       amazon q is not installed:
     Error: Test length exceeded max duration: 30 seconds
```

**Review by hayemaxi — APPROVED** [review]
Thanks for the quick turnaround!

**Pull request merged**
