### PR TITLE
UI: Lambda invoke style updates

### PR DESCRIPTION
**Pull request by JadenSimon**
## Before
Screen Shot 2021-09-20 at 9 43 29 AM
Screen Shot 2021-09-20 at 9 43 12 AM

## After
Screen Shot 2021-09-20 at 9 31 05 AM
Screen Shot 2021-09-20 at 9 31 28 AM

And for Cloud9 (temporary style sheet):
Screen Shot 2021-09-20 at 12 41 57 PM
Not currently able to get any exact matches with the current theme since none of the variables are exposed. Instead I'm applying tints and shades to the background color, which is basically a darker version of the current theme. Because of color composition I'm pretty restricted in how much tinting/shading I can do before the saturation diverges significantly. Since there's only 5 themes this isn't too bad, and it looks 'close enough' on each one. 

### Themes
Kapture 2021-09-20 at 13 19 55

### Collapseable panels
The `Additional Fields` (previously a button called 'More Fields') and `Payload` have been moved to collapseable panels. They start pre-collapsed.

### Checkboxes
Boolean fields are now checkboxes

### Misc. fixes
* Fixed issue where empty payload field would cause an error

# TODO
Need to check compatibility with different browsers for C9. The only issues would be modifying the 'select' tag since it uses webkit. Only checked firefox so far, chrome should be fine since VSC uses chromium. The webview still uses native select tags; ideally we have our own element so it can be consistently styled across operating systems and browsers.

The new style fits with every theme I've tested with the exception of VS Code's 'high contrast'. There's a few things missing for that one since I didn't add selectors.

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by justinmk3 — APPROVED** [review]

**Comment by justinmk3** [comment]
This is great. Are the Save/Invoke buttons always visible? Would like to also try that in our other forms. Having to scroll-to-submit is a pain.

**Comment by breedloj** [comment]
Huge improvement! Nice!

**Review by breedloj — APPROVED** [review]

**Comment by JadenSimon** [comment]
> Are the Save/Invoke buttons always visible?

Yeah it's using a 'sticky' position for that div. I didn't pay too much attention to that part of the form, but later on it'd be nice to style it as if it were apart of the window rather than as a free-floating panel. On Cloud9 I had to make the background transparent since there was no way to theme the panel correctly.

**Pull request merged**
