### PR TITLE
refactor(amazonq): Remove collectFiles instrumentation

### PR DESCRIPTION
**Pull request by jpinkney-aws**
## Problem
- Follow up on the previous remove trackPerformance PR, we no longer need collectFiles telemetry since the data isn't reliable in the extension host
- integ tests are failing because of this

## Solution
- Remove the instrumentation

### CODE REVIEW

**Comment by Hweinstock** [comment]
So if we rebase to current master, this should resolve the final integ tests failing?

**Comment by justinmk3** [comment]
new integ failures:

```
  1) visualizeStateMachine
       opens up a webview when there is an active text editor:
     AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_1.default.ok(result)

      at Context.<anonymous> (/codebuild/output/src3721222019/src/github.com/aws/aws-toolkit-vscode/packages/core/src/testInteg/stepFunctions/visualizeStateMachine.test.ts:108:16)

  2) visualizeStateMachine
       correctly displays content when given a sample state machine:
     AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_1.default.ok(result)

      at Context.<anonymous> (/codebuild/output/src3721222019/src/github.com/aws/aws-toolkit-vscode/packages/core/src/testInteg/stepFunctions/visualizeStateMachine.test.ts:117:16)

  3) visualizeStateMachine
       correctly displays content when given a sample state machine in yaml:
     AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_1.default.ok(result)

      at Context.<anonymous> (/codebuild/output/src3721222019/src/github.com/aws/aws-toolkit-vscode/packages/core/src/testInteg/stepFunctions/visualizeStateMachine.test.ts:140:16)

  4) visualizeStateMachine
       update webview is triggered when user saves correct text editor:
     AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_1.default.ok(result)

      at Context.<anonymous> (/codebuild/output/src3721222019/src/github.com/aws/aws-toolkit-vscode/packages/core/src/testInteg/stepFunctions/visualizeStateMachine.test.ts:164:16)

  5) visualizeStateMachine
       doesnt update the graph if a seperate file is opened or modified:
     AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_1.default.ok(result)

      at Context.<anonymous> (/codebuild/output/src3721222019/src/github.com/aws/aws-toolkit-vscode/packages/core/src/testInteg/stepFunctions/visualizeStateMachine.test.ts:197:16)

globalSetup: after()
```

**Comment by Hweinstock** [comment]
I believe these are fixed in https://github.com/aws/aws-toolkit-vscode/pull/5724.

**Pull request merged**
