### PR TITLE
TSLint to ESLint request for comments

### PR DESCRIPTION
**Pull request by hunterwerlla**
Migrating from a bespoke TSLint ruleset to a more standard configuration. I think this configuration is better because it showed a bunch of issues that seem legitimate when the config was added. This PR only fixes some of the issues that have a few violations as to not be a giant diff, and to point out some new categories of issues detected with the new rules.

Some Key differences:
- The circular imports rule is gone,~~this should be handled by the typescript compiler and webpack though? thoughts?~~ it's now part of webpack
- ~~Tests are not getting linted because they produce thousands of promise errors. Do we really need to lint them? maybe we should disable a subset instead and still lint tests? thoughts?~~ Tests are being linted now
- The rule list has been shorted a lot and only disables these rules (other disables should be fixed) 
```
        '@typescript-eslint/no-empty-function': 'off',
        '@typescript-eslint/no-unused-vars': 'off',
        'no-constant-condition': ['error', { checkLoops: false }],
        'no-empty': 'off',
``` 
- JS files are currently not being linted, more work is required to make them pass as well

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by justinmk3** [comment]
> * The imports rule is gone, this should be handled by the typescript compiler and webpack though? thoughts?

I wouldn't miss it :) What advantage does the "ordered imports" rule provide? I suppose it avoids some merge conflicts... 

> * Tests are not getting linted because they produce thousands of promise errors. Do we really need to lint them? maybe we should disable a subset instead and still lint tests? thoughts?

+1 for linting tests, it can catch worthwhile mistakes.

**Comment by awschristou** [comment]
> I wouldn't miss the "ordered imports" rule :) I suppose it avoids some merge conflicts...

+1 for avoiding merge conflicts. Lets assume there will be more feature branches in concurrent development at a given time, across different repo forks (eg: public/private development). This will save some pain. package.nls.json is an example where painpoints arise, where if the keys were sorted we would have had less conflicts.

**Comment by ckant** [comment]
> Tests are not getting linted because they produce thousands of promise errors. Do we really need to lint them? maybe we should disable a subset instead and still lint tests? thoughts?

I'm curious to see if there's a systematic thing we're doing that we can fix with the promises. Perhaps we can identify a pattern and tweak the promise rule. I think it'd be worth it to try to set the same standards for tests as we do source files. Following the same guidelines should make the tests more readable/maintainable and allow us to prevent test bugs that cause tests to not test what they're supposed to test. 

test

**Comment by hunterwerlla** [comment]
> > * The imports rule is gone, this should be handled by the typescript compiler and webpack though? thoughts?
> 
> I wouldn't miss the "ordered imports" rule :) I suppose it avoids some merge conflicts...
> 
> Very much in favor of "no-circular-imports" rule, though.
> 
> > * Tests are not getting linted because they produce thousands of promise errors. Do we really need to lint them? maybe we should disable a subset instead and still lint tests? thoughts?
> 
> +1 for linting tests, it can catch worthwhile mistakes.

I re-added the ordered imports rule per feedback

I don't disagree on tests, we need a workaround for the issue though

no-cirular-imports requires path data which makes it seem to me like we should do it in webpack instead. otherwise we will have a 3rd place with path information.

**Comment by hunterwerlla** [comment]
Upon further investigation, with the currently turned off rules, we can lint tests but it will either require a big diff or turning off a lot more rules, thoughts?

**Pull request merged**
