### PR TITLE
test/integ: SAM "F5 debugging" with target=api

### PR DESCRIPTION
**Pull request by justinmk3**
## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by justinmk3** [comment]
```
2020-12-08 18:02:56 [ERROR]: Timeout while waiting for command: "sam local start-api"
2020-12-08 18:02:56 [WARN]: [Error: Timeout while waiting for command: "sam local start-api"
	at DefaultSamLocalInvokeCommand.<anonymous> (/Volumes/workplace/aws-toolkit-vscode/dist/src/shared/sam/cli/samCliLocalInvoke.js:117:27)
	at Generator.next (<anonymous>)
	at /Volumes/workplace/aws-toolkit-vscode/dist/src/shared/sam/cli/samCliLocalInvoke.js:12:71
	at new Promise (<anonymous>)
	at /Volumes/workplace/aws-toolkit-vscode/dist/src/shared/sam/cli/samCliLocalInvoke.js:8:12
	at /Volumes/workplace/aws-toolkit-vscode/dist/src/shared/sam/cli/samCliLocalInvoke.js:111:61]
2020-12-08 18:02:56 [ERROR]: Failed to start local API Gateway: Timeout while waiting for command: "sam local start-api" Timeout while waiting for command: "sam local start-api"
2020-12-08 18:02:56 [INFO]: Waiting for SAM application to start...
```

**Comment by JadenSimon** [comment]
The Python tests failing are probably related to the Python extension not activating. Should be transient?

**Review by JadenSimon — APPROVED** [review]
This will break Go integration tests once merged :(
Will probably add a temporary exemption for it.

**Pull request merged**
