### PR TITLE
feat!(regions): remove "aws.onDefaultRegionMissing" setting

### PR DESCRIPTION
**Pull request by justinmk3**
## Problem

The "Do you want to add this region?" prompt is too complex, in terms of both UI and code, for the problem it addresses.

## Solution

- remove `aws.onDefaultRegionMissing`
- remove the `Yes, and don't ask again` option. The complexity in UI  and code is not worth it. This prompt rarely occurs...
- store "don't ask again" in the standard `aws.suppressPrompts` setting.

image

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by JadenSimon — APPROVED** [review]

**Comment by JadenSimon** [comment]
>  apt-get -qq install -y java-1.8.0-amazon-corretto-jdk java-11-amazon-corretto-jdk

Failing for integ.

**Comment by justinmk3** [comment]
> Also, why do we swallow all output for installation? Was it really noisy or something?
yes

**Pull request merged**
