### PR TITLE
Fix bug where SAM Invoke would only use one resource from the template

### PR DESCRIPTION
**Pull request by hunterwerlla**
- Make CloudFormation registry more lenient, explicitly say that there are other resource types (string), and that other properties can exist
- Pass all resources into invoke instead of only the function we are running
## Related Issue(s)
https://github.com/aws/aws-toolkit-vscode/issues/1352

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by justinmk3 — APPROVED** [review]
really nice fix!

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/1361 might avoid some of the problems here. +1 for merging this meanwhile.

**Comment by hunterwerlla** [comment]
> #1361 might avoid some of the problems here. +1 for merging this meanwhile.

Yeah it should fix this since we don't make a new handler, cool

**Pull request merged**
