### PR TITLE
UI: Remove `asyncIterator` shim

### PR DESCRIPTION
**Pull request by JadenSimon**
## Problem
~Not handling the case where a generator yields an empty array (as opposed to not yielding at all)~
The above was not the problem. It was because the shim clobbers symbols when you build as a VSIX.

## Solution
~Guard against callers passing in empty arrays everywhere.~

~Basically need to be careful about what we send through the API since they may not always handle these edge cases for us.~

We should guard anyway but remove the shim because it's wrong.

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by JadenSimon** [comment]
Thinking back, that 'shim' has caused me so many problems with async iterables but I never connected the dots...

**Review by justinmk3 — APPROVED** [review]
Should asyncIteratorShim.ts itself be deleted as well?

**Comment by JadenSimon** [comment]
Oh oops forgot to delete it.

**Pull request merged**
