### PR TITLE
config(amazonq): enable more languages in generateCompletion requests

### PR DESCRIPTION
**Pull request by Will-ShaoHua**
## Problem

Per product team's request, unblock requests of the following language to the service which will be ready soon. (thus not calling it out as a "feat" as it's not supported yet)

image

## Functional test

https://github.com/user-attachments/assets/bcc7646c-d38c-4d4b-8ee3-d67dc7c92154

https://github.com/user-attachments/assets/a6b62ac5-9e40-4fc1-85f5-24e274b75908

https://github.com/user-attachments/assets/d74d56f4-66cc-49ba-9944-95dd826471b8

https://github.com/user-attachments/assets/70bc7ef5-4ee5-4699-801f-97e8cb694caa

https://github.com/user-attachments/assets/8451d791-baa0-44a1-836a-da5ff5bf7cdb

https://github.com/user-attachments/assets/d9bad39d-32ab-4632-96f5-1922ebf807cc

---

License: I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by andrewyuq — APPROVED** [review]

**Comment by Will-ShaoHua** [comment]
will attach functional test screen recording

**Comment by nkomonen-amazon** [comment]
changelog item?

**Review by nkomonen-amazon — APPROVED** [review]

**Comment by Will-ShaoHua** [comment]
@nkomonen-amazon Nick for this one we don't want to mention it in changelog

**Comment by Will-ShaoHua** [comment]
2636 passing (5m)
  13 pending
  1 failing
  1) Auth
       promptForConnection
         reauthenticates a connection if the user selects an expired one:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_1.default.ok(!refreshedConnItem.description?.match(/expired/i))

      + expected - actual

      -false
      +true

**Pull request merged**
