### PR TITLE
Upgrade aws-ssm-language-service version and fix integration tests

### PR DESCRIPTION
**Pull request by scecan**
## Description

This pr has the following changes:
1. Upgrade aws-ssm-language-service version to 1.0.0
2. Fixed packaging so the integration tests can run. The issue was that aws-ssm-language-service artifacts weren't being copied to `"dist/"` before running integration tests.

## Testing

1. run all integration tests successfully
2. built the VSIX
3. installed the VSIX to test that SSM language service is properly initialized

## Checklist

- [x] I have read the **README** document
- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [ ] A short description of the change has been added to the changelog using the script `npm run newChange`

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bryceitoc9** [comment]
/runintegrationtests (note that this command needs to be run by a member of the AWS IDEs team)

**Comment by justinmk3** [comment]
This fixes the hang, thanks! The failing `Integration Tests [stable]`  is a known issue, unrelated.

**Comment by justinmk3** [comment]
Needs a rebase since https://github.com/aws/aws-toolkit-vscode/pull/1319 was merged

**Comment by scecan** [comment]
> Needs a rebase since #1319 was merged

done

**Review by bryceitoc9 — APPROVED** [review]

**Pull request merged**
