### PR TITLE
feat(codewhisperer): add repo url to reference tracker

### PR DESCRIPTION
**Pull request by zixlin7**
## Problem
to provide link to the referenced repo to reference tracker log
## Solution
- if `url` is present in the reference, we will show link to the repo instead of link to license:
Screen Shot 2022-08-03 at 2 50 32 PM
- if `url` is missing, we will keep the current behavior with link to the license and repo name:
Screen Shot 2022-08-03 at 3 28 21 PM

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by leigaol** [comment]
I think the service-2.json needs to be updated with this change.

**Comment by zixlin7** [comment]
> I think the service-2.json needs to be updated with this change.

@leigaol it's already updated with #2795, not sure why it's still failing, anything else I miss?

**Comment by justinmk3** [comment]
src/codewhisperer/service/referenceLogViewProvider.ts(87,27): error TS2339: Property 'url' does not exist on type 'Reference'.

> > I think the service-2.json needs to be updated with this change.
> 
> @leigaol it's already updated with #2795, not sure why it's still failing, anything else I miss?

Hmm. CI log shows that the client + d.ts file generated. 

/retrybuilds

**Comment by JadenSimon** [comment]
@zixlin7

Try merging `master` into this branch. I think the Linux tests don't do this automatically.

**Comment by zixlin7** [comment]
> @zixlin7
> 
> Try merging `master` into this branch. I think the Linux tests don't do this automatically.

will try that, thanks!

**Review by JadenSimon — APPROVED** [review]
Unit tests look bloated but there's only two so it's ok for now.

**Review by fangwade007 — APPROVED** [review]

**Comment by justinmk3** [comment]
Doesn't this deserve a changelog entry? Something like:

    CodeWhisperer: References include a link to the source repository if possible.

**Pull request merged**
