### PR TITLE
feat(amazonq): added mynah updated beta package for feature dev

### PR DESCRIPTION
**Pull request by 32teeth**
## Solution

Update to mynah package to enable focus tab from notification

---

License: I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jpinkney-aws** [comment]
Can you explain more about why we would move to a beta dependency?

**Comment by 32teeth** [comment]
> Can you explain more about why we would move to a beta dependency?

@dogusata has implemented a feature to be able to select a tab by ID without passing an eventID in the NPM release

> I've released a beta version which removes the eventId check from the selectTab method.
> Please use version number as https://www.npmjs.com/package/@aws/mynah-ui/v/4.16.1-beta.1
> When there is a new production release, it will contain this change. (Will be 4.16.1 or above)

**Comment by 32teeth** [comment]
I will amend the commit message this evening

**Comment by justinmk3** [comment]
It looks like this may have a customer-facing impact that can be described in the changelog. The changelog is presented to users by VSCode and the marketplace. It is a "micro-blog" for advertising improvements to users. It is the primary way of communicating changes to customers.

1. Review the [changelog guidelines](https://github.com/aws/aws-toolkit-vscode/blob/master/CONTRIBUTING.md#changelog).
2. Add a new changelog entry: `npm run newChange -w packages/amazonq` or `npm run newChange -w packages/toolkit`

**Comment by jpinkney-aws** [comment]
FWIW 4.16.1 (the newest mynah ui version) has just been released so I don't think the beta version is relevant anymore

**Comment by 32teeth** [comment]
Thanks. Closing out

**Pull request closed without merging**
