### PR TITLE
feat(q-proactive-scan): remove file scans for Builder Id, add timeout limits

### PR DESCRIPTION
**Pull request by ashishrp-aws**
## Problem
Change Timeout limits for project scan and File scans. No Auto Scan status bar options for Free Users(BuilderId) and no file scans enabled for Builder Id users.
## Solution
- Added Timeout Limits for Project and File Scans.
- Disabled File scan for BuilderID users.
- Removed status bar Code scan toggle option for Builder Id Users.

Compiled and run a debug extension
Screenshot 2024-04-15 at 11 04 43 AM

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ashishrp-aws** [comment]
\runintegrationtests

**Review by laileni-aws — APPROVED** [review]

**Pull request merged**
