### PR TITLE
CI: Add test matrix to GitHub actions workflows

### PR DESCRIPTION
**Pull request by hunterwerlla**
## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by bryceitoc9 — APPROVED** [review]

**Comment by justinmk3** [comment]
I see 2 redundant jobs: `Windows nodejs (12.x)` and `macOS nodejs (12.x)`.

**Comment by hunterwerlla** [comment]
> I see 2 redundant jobs: `Windows nodejs (12.x)` and `macOS nodejs (12.x)`.

Those are the old jobs, since they are required they still show up. They will not run anymore with this change

**Review by justinmk3 — APPROVED** [review]
This will slow down CI if the jobs are not parallelized. Depends on how much capacity github/azure gives us.

**Comment by hunterwerlla** [comment]
> This will slow down CI if the jobs are not parallelized. Depends on how much capacity github/azure gives us.

I mean sure, but they are running in parallel on this PR. We need to be testing min and insiders for all of our platforms.

**Pull request merged**
