### PR TITLE
AmazonQ: Add cwsprCredentialStartUrl field to chat telemetry events

### PR DESCRIPTION
**Pull request by ppiliaev**
The new field contains the start URL of the current SSO connection. This will allow tracing back chat events to the originating SSO session.

## Problem
We missed this field for the AmazonQ experience

## Solution
New field introduced

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by justinmk3 — APPROVED** [review]
Waiting for cwchat team member to approve.

**Comment by justinmk3** [comment]
the failing test will be fixed by https://github.com/aws/aws-toolkit-vscode/pull/4437

please rebase after that is merged.

**Review by barbepatAWS — APPROVED** [review]

**Comment by leigaol** [comment]
I believe the event definition change needs to be checked in to aws-toolkit-common.

**Review by leigaol — APPROVED** [review]
Please move the override to common library whenever possible. This avoids duplicating the overrides in different platforms.

**Review by nkomonen-amazon — APPROVED** [review]

**Pull request merged**
