### PR TITLE
package: increase minimum vscode to 1.68

### PR DESCRIPTION
**Pull request by justinmk3**
## Problem

Since #3328 5439f9527224d8d1c0b98cd9941ee55a0cefb9ae , CI job "Integration Tests - minimum" fails (timeout) of some (not all) "invokes and attaches" tests:

    5 failing
    1) SAM Integration Tests
         SAM runtime: python 3.10 (ZIP)
           Starting with a newly created python 3.10 (ZIP) SAM Application...
             target=api: invokes and attaches on debug request (F5):
       Error: Test length exceeded max duration: 300 seconds
    ...

## Notes

- Major difference is that [vscode 1.65 has nodejs 14, while vscode 1.66+ has nodejs 16](https://github.com/aws/aws-toolkit-vscode/pull/3315#issuecomment-1506896655).
- cloud9-classic has vscode extension host 1.68 + nodejs 16 ~~nodejs 12(!).~~
- cloud9-codecatalyst has vscode 1.68 + node 14.19

## Testing

Tested in vscode local, vscode remote codecatalyst, cloud9-classic, cloud9-codecatalyst.

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by nkomonen-amazon — APPROVED** [review]

**Comment by justinmk3** [comment]
fatal: unable to access 'https://github.com/awslabs/goformation/': Failed to connect to github.com port 443 after 131151 ms: Connection timed out


? https://www.githubstatus.com/history

**Comment by JadenSimon** [comment]
Could this be the problem?
https://github.com/aws/aws-toolkit-vscode/blob/82d4c51f1e73342ce069dcb50861d7d2d002d77e/src/integrationTest/cloudformation/templateRegistry.test.ts#L53-L55 

I have no clue why it would matter but it is one difference.

**Comment by justinmk3** [comment]
```
Cloning into '/codebuild/output/src577833252/src/github.com/aws/aws-toolkit-vscode/node_modules/.zzz-awssdk2'...

fatal: unable to access 'https://github.com/aws/aws-sdk-js.git/': Failed to connect to github.com port 443 after 130288 ms: Connection timed out
```

**Pull request merged**
