### PR TITLE
UX: add Getting Started walkthroughs

### PR DESCRIPTION
**Pull request by breedloj**
## Problem
Users often give feedback that configuring the Toolkit is difficult. While helpful documentation does exist the bulk of it is contained on the AWS Documentation portal.

## Solution
VSCode extensions may now contribute walkthroughs that are surfaced via the Welcome screen. This change adds a series of walkthroughs to help new users quickly set up the Toolkit by setting up their credentials, Explorer view regions, and configure their toolchain for SAM app development.

Screen Shot 2021-07-28 at 2 30 02 PM

Walkthroughs surface markdown content that support most formatting, external linking, as well as the ability to trigger extension commands. Walkthrough steps can be marked completed by a user or by way of [configurable completion events](https://code.visualstudio.com/api/references/contribution-points#Completion-events).

Screen Shot 2021-07-29 at 10 14 36 AM

Once walkthrough steps have been marked as completed the walkthrough is no longer displayed as a top level item on the welcome screen but can be accessed a 'Show All...` toggle that opens a list of available walkthroughs.

Screen Shot 2021-07-28 at 2 32 09 PM

As a rule of thumb I have attempted to keep this drop of walkthroughs very action oriented and concise. I link out to external documentation when a deeper dive into a specific topic (for instance, setup of IAM users and retrieval of credentials) may be desired. I also surface ways to quickly perform actions directly from the walkthrough (for example, adding a region to the Explorer) while also showing how this would be accessed otherwise to educate the user.

We can expand these walkthroughs over time to cover more advanced or task oriented topics. `when` clauses can help us control when walkthoughs should be surfaced to users. For example, if we detect a user has not made use of a particular feature we can highlight it via a walkthrough. In the case of this initial set I'm not sure if there's a good all encompassing way to detect if someone is a beginner, but I am open to suggestions here.

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bryceitoc9** [comment]
Does this fight with the quickstart for attention? Quickstart is definitely necessary for Cloud9 and the marketplace page, but will this and the quickstart popping up in the users' face on first activation be too much?

**Review by justinmk3 — APPROVED** [review]
Nice layout. Let's try it...

**Comment by breedloj** [comment]
> Does this fight with the quickstart for attention? Quickstart is definitely necessary for Cloud9 and the marketplace page, but will this and the quickstart popping up in the users' face on first activation be too much?

It's a fair point to raise but I don't think this is going to be too intrusive. I'm hopeful that in time this feature can replace the quick start entirely but that will require a richer feature set in the API as well as support from Cloud9. Meanwhile there is some overlap but walkthroughs are exposed pretty quietly by VSC. Worst case, someone doesn't want or need the assistance and X'es out the walkthrough, hiding it until we either update the walkthrough or they reinstall VSC, so it's a pretty low nag point and hopefully ends up helping some of the folks who need it (let's see).

**Comment by bryceitoc9** [comment]
+1 to full migration to walkthroughs in the future. This is less of a question about "right place" and more of a question about "right time".

**Comment by justinmk3** [comment]
aws-toolkit-commandpalette.png could be cropped to take less vertical space

**Review by JadenSimon — APPROVED** [review]

**Pull request merged**
