### PR TITLE
fix codewhisperer:  clean codewhisperer states afterEach

### PR DESCRIPTION
**Pull request by Will-ShaoHua**
## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by justinmk3 — APPROVED** [review]

**Comment by Will-ShaoHua** [comment]
@justinmk3 yea, I suspect the test failure is caused by incorrect states cleaning

**Comment by Will-ShaoHua** [comment]
@justinmk3 btw what's the command to re-run the github CI here

**Comment by justinmk3** [comment]
@Will-ShaoHua still seeing this issue in CI so I re-opened https://github.com/aws/aws-toolkit-vscode/issues/4238

**Comment by Will-ShaoHua** [comment]
ack, will look into it

**Pull request merged**
